version: '3'
services:
  flask-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - backend
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - backend
