version: '3'
services:
  flask-server:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      # - mongodb
      - redis
    volumes:
      - .:/code
  # mongodb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27018:27018"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #     MONGO_INITDB_DATABASE: slack-bot
  #   volumes:
  #     - mongodb-data:/data/db
  redis:
    image: redis:7.0.0
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - redis-data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
